In [20]:
import pandas as pd
import sqlite3

url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/imdb_1000.csv"

df = pd.read_csv(url)

df

df.head()

df.tail()

df.info()

df.shape

df.columns

df.dtypes

df.describe()

df.describe(include='all')

df.isnull().sum()

df['genre'].value_counts()

df['genre'].unique()

df.corr(numeric_only=True)


df.to_excel("imdb_movies.xlsx", index=False)


df_excel = pd.read_excel("imdb_movies.xlsx")

df_excel.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 979 entries, 0 to 978
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   star_rating     979 non-null    float64
 1   title           979 non-null    object
 2   content_rating  976 non-null    object
 3   genre           979 non-null    object
 4   duration        979 non-null    int64
 5   actors_list     979 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 46.0+ KB

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [2]:
conn = sqlite3.connect("imdb.db")

df.to_sql("movies", conn, if_exists="replace", index=False)

pd.read_sql("SELECT * FROM movies LIMIT 5", conn)

pd.read_sql("SELECT COUNT(*) AS Total_Movies FROM movies", conn)

pd.read_sql("""
SELECT title, star_rating
FROM movies
ORDER BY star_rating DESC
LIMIT 10
""", conn)

pd.read_sql("""
SELECT genre, COUNT(*) AS Total
FROM movies
GROUP BY genre
ORDER BY Total DESC
""", conn)

pd.read_sql("""
SELECT genre, AVG(star_rating) AS Average_Rating
FROM movies
GROUP BY genre
ORDER BY Average_Rating DESC
""", conn)

pd.read_sql("""
SELECT title, genre, star_rating
FROM movies
WHERE content_rating='PG-13'
LIMIT 10
""", conn)

                                               title      genre  star_rating
0                                    The Dark Knight     Action          9.0
1      The Lord of the Rings: The Return of the King  Adventure          8.9
2  The Lord of the Rings: The Fellowship of the Ring  Adventure          8.8
3                                          Inception     Action          8.8
4                                       Forrest Gump      Drama          8.8
5              The Lord of the Rings: The Two Towers  Adventure          8.8
6                                       Interstellar  Adventure          8.7
7                                  Life Is Beautiful     Comedy          8.6
8                       Once Upon a Time in the West    Western          8.6
9                              The Dark Knight Rises     Action          8.5

In [23]:
import pandas as pd
import os
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/imdb_1000.csv"

df = pd.read_csv(url)

df.to_csv("imdb_movies.csv", index=False)

df.to_excel("imdb_movies.xlsx", index=False)

df.to_json("imdb_movies.json", orient="records", indent=4)
print("CSV, Excel, json files exported successfully.")


os.listdir()

CSV, Excel, json files exported successfully.

['Untitled10.ipynb',
 'trial.txt',
 'Untitled7.ipynb',
 '.eclipse',
 '.config',
 'Downloads\\data1.xlsx',
 'job.csv',
 'Music',
 'avgpay.awk',
 'random_forest_model.pkl',
 'Image classification.ipynb',
 '.condarc',
 '220701901',
 'Untitled12.ipynb',
 'Untitled5.ipynb',
 'Untitled1.ipynb',
 'imdb.db',
 'employees details.csv',
 'Untitled16.ipynb',
 'Time series 1',
 '.DS_Store',
 'eclipse',
 'nltk_data',
 'banker',
 'h.awk',
 '.CFUserTextEncoding',
 '.xonshrc',
 'Student Mental health  .numbers',
 'excel1.xlsx',
 'banker.c.save',
 'anaconda_projects',
 'Student Mental health  2.numbers',
 'Untitled3.ipynb',
 'Untitled14.ipynb',
 'Student Mental health (1).csv',
 'Untitled.ipynb',
 '.vijay.java.swp',
 '.zshrc',
 '.packettracer',
 '.templateengine',
 'Book1.xlsx',
 'edgedetection.ipynb',
 '5000.csv',
 'Untitled4.ipynb',
 'cancer.csv',
 '.local',
 'Untitled13.ipynb',
 'Kamal BME 50',
 'Untitled6.ipynb',
 'projects',
 'Pictures',
 'install.sh',
 'Untitled11.ipynb',
 'imdb_movies.csv',
 'm.sh',
 'face.webp',
 'imdb_movies.xlsx',
 'Student Mental health.csv',
 'employees  details.xlsx',
 '220701519',
 '.nuget',
 'knn.ipynb',
 'Untitled15.ipynb',
 'login.html',
 'Student Mental health  1.numbers',
 '.zsh_history',
 'Untitled2.ipynb',
 '.p2',
 '.ipython',
 'imdb_movies.html',
 'Desktop',
 'Library',
 'eclipse-workspace',
 'html',
 '230901122 Yokesh Data wrangling 2',
 '.matplotlib',
 '.lesshst',
 'naive',
 'Untitled17.ipynb',
 '.spyder-py3',
 '.IdentityService',
 'seaborn-data',
 '.csv',
 '.android',
 'Data visualization 3',
 'scikit_learn_data',
 'salary.csv',
 'untitled.txt',
 '500',
 'load',
 'Untitled19.ipynb',
 'PacketTracer7',
 'iris.csv',
 'a.out',
 'Public',
 'excel1 (1).xlsx',
 'imdb_movies.json',
 'Cisco Packet Tracer 8.2.1',
 '210701025',
 '.idlerc',
 'untitled1.txt',
 'hadoop',
 '.tcshrc',
 'Untitled20.ipynb',
 '.virtual_documents',
 '.anaconda',
 '500.csv',
 'import pandas as pd.py',
 '230901044 KANISHKAR',
 'employees details (1).csv',
 'untitled2.txt',
 'Kishore Kumar 220701512',
 'Untitled8.ipynb',
 '.ssh',
 'Movies',
 '.dotnet',
 'Applications',
 'flower.jpg',
 '.gradle',
 'Jack',
 'saranraj',
 '220701213',
 '.Trash',
 '.ipynb_checkpoints',
 'Untitled18.ipynb',
 'hadoop.pub',
 '.jupyter',
 'Yokesh 230901122 Data Visulaization 2',
 '.keras',
 'home_price.csv',
 'face.jpeg',
 'pandas 2.',
 '.npm',
 'excel2.xlsx',
 'Documents',
 'pandas2',
 'yuvesh d data cleaning and preparation of data frame',
 '.pyenv',
 'employee.txt',
 'banker.c',
 'decision.csv',
 '.mono',
 '.vscode',
 '.m2',
 'NetBeansProjects',
 '.bash_profile',
 '.swiftpm',
 'cars.csv',
 'employee230901052.csv',
 'Downloads',
 'tree2.png',
 '.continuum',
 '.cache',
 'Data visualization2',
 'rnn.py',
 'Untitled9.ipynb',
 'drowsiness_detection',
 'login',
 '.bash_history',
 '.viminfo',
 '.zsh_sessions',
 'tree1.png',
 '220701513 Prashanth P',
 'pandas',
 'excel3.xlsx',
 '.conda',
 'Downloads\\data2.xlsx',
 'dfs.py',
 'Numpy1',
 'Untitled21.ipynb',
 'miniconda3']